### ISSUE TITLE
Demo not rendering correctly in Safari

### ISSUE THREAD

**Issue by jakemumu** [ankane/chartkick#607] opened 2023-02-19 05:38 UTC
**Describe the bug**

I was giving this a shot today -- it's awesome, but I almost didn't because I use safari and the demo pages didn't loaded correctly

**To reproduce**

Load demo page, see this: 

<img width="998" alt="Screenshot 2023-02-18 at 9 38 06 PM" src="https://user-images.githubusercontent.com/11396462/219928702-c7e212a0-3414-4978-a028-821c5bf212fa.png">

**Comment by ankane** [comment] 2023-02-19 05:55
Hey @jakemumu, thanks for reporting. Just pushed a fix (was caused by some changes made earlier this week).

**Closed by ankane** 2023-02-19 05:55 UTC

**Comment by jakemumu** [comment] 2023-02-19 06:36
Awesome! Looks great for me now. Thanks so much for these awesome libraries you create they're really next level!
