### ISSUE TITLE
Display google charts negative value left from positive instead of right

### ISSUE THREAD

**Issue by TeTiRoss** [ankane/chartkick#258] opened 2016-05-19 10:08 UTC
I'm using chartkick gem for building Google Charts in my rails app. But I have a problem with displaying negative values in line chart. Negative value goes after the positive instead of before. 

I have tried to google how to fix it, but didn't find any solution.

**Comment by ankane** [comment] 2016-05-20 04:18
Hi @TeTiRoss, can you give more details or a screenshot?  Not sure I follow.

**Comment by TeTiRoss** [comment] 2016-05-20 07:30
@ankane yes, here is screenshot and code sample: 
![Image of Yaktocat]
(http://i.stack.imgur.com/v6pTp.png)

```ruby
<%= line_chart([{name: 'name_1', data: @data_for_chart_1},
                {name: 'name_2', data: @data_for_chart_2}], discrete: true,
                xtitle: "Cut Expenses By ($)", ytitle: "Max. Home Price ($)",
                colors: ["#2E3192", "red"], library: {title: "Cutting Expenses Makes Higher Priced Homes Affordable", curveType: "none", pointSize: 0, legend: { position: "bottom" }}, id: "chart" ) %>
```
I tried to change `discrete: true` to `false`, so it will be continuous axis, but in that way I have date in the tooltips. @data_for_chart_1 and @data_for_chart_2 are integer keys and values. 
```ruby
{0=>173929, 70=>185474, 140=>197018, 210=>208563, 280=>220108, 350=>231653, 420=>243197, 490=>254742, 560=>266287, 630=>270900}
```

**Comment by TeTiRoss** [comment] 2016-05-24 07:56
So, are there any solutions for this?

**Comment by TeTiRoss** [comment] 2016-05-24 12:42
So, are there any solutions for this?
And one more question.
Is it possible to not break line in this case:
![Image of chart]
(https://pp.vk.me/c636027/v636027758/c11a/Tz00KDcufrM.jpg)

**Comment by TeTiRoss** [comment] 2016-05-24 12:43
@ankane are there any solutions for this?
And one more question.
Is it possible to not break line in this case:
![Image of chart]
(https://pp.vk.me/c636027/v636027758/c11a/Tz00KDcufrM.jpg)

**Comment by RobWu** [comment] 2016-05-30 14:19
Same for me

![screen shot 2016-05-30 at 16 18 57](https://cloud.githubusercontent.com/assets/237810/15651841/541e57a0-2682-11e6-874d-56380e424f72.png)

**Comment by RobWu** [comment] 2016-05-30 14:21
If i use google library alone. it works fine.. looks like a chartkick  issue.

**Comment by RobWu** [comment] 2016-05-30 14:46
same issue with highchairs.

same issue with release 0.0.5 too..

**Comment by RobWu** [comment] 2016-05-30 15:11
Can be reproduced with js only:

```javascript
new Chartkick.ColumnChart("chart-2", {"-11":0,"-10":0,"-9":0,"-8":0,"-7":0,"-6":0,"-5":0,"-4":0,"-3":0,"-2":0,"-1":0,"0":0,"1":0,"2":0,"3":1,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0}, {});
```

**Comment by RobWu** [comment] 2016-05-30 20:13
```javascript
JSON.parse("{ \"-11\":0,\"-10\":0,\"-9\":0,\"-8\":0,\"-7\":0,\"-6\":0,\"-5\":0,\"-4\":0,\"-3\":0,\"-2\":0,\"-1\":0,\"0\":0,\"1\":0,\"2\":0,\"3\":1,\"4\":0,\"5\":0,\"6\":0,\"7\":0,\"8\":0,\"9\":0,\"10\":0,\"11\":0,\"12\":0,\"13\":0,\"14\":0,\"15\":0,\"16\":0,\"17\":0,\"18\":0,\"19\":0,\"20\":0,\"21\":0 }")
```
Creates the same **wrong** order as in the charts.. So maybe json order issue..


With arrays:
```javascript
new Chartkick.ColumnChart("chart-2", [[-11,0],[-10,0],[-9,0],[-8,0],[-7,0],[-6,0],[-5,0],[-4,0],[-3,0],[-2,0],[-1,0],[0,0],[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0],[11,0],[12,0],[13,0],[14,0],[15,0],[16,0],[17,0],[18,0],[19,0],[20,0],[21,0]], {});    
```

Makes same **wrong** chart..

**Comment by TeTiRoss** [comment] 2016-05-31 05:35
Started using HighCharts library alone, cause didn`t find any solution for this.

**Comment by ankane** [comment] 2016-12-05 04:05
Thanks for reporting @TeTiRoss and @RobWu 👍  This is now fixed on master.

**Closed** 2016-12-05 04:05 UTC
